#!/usr/bin/env bash

clear

# Let's start some docs

DEMO=demo1

cat > ${DEMO}.pmd  <<'EOF'
# Demo Doc

This is the start of our docs

Let's have a picture

![A Cool Meme](../../wiki/images/meme.jpg)

That's it folks
EOF

echo Here is some Markdown
echo ----------------------------------

cat ${DEMO}.pmd
echo ----------------------------------
read -p "Press Any Key to create a PDF" -n 1

echo 'pandoc  -V documentclass=article --number-sections --standalone -f markdown+startnum+smart+yaml_metadata_block --filter pandoc-fignos  -o ${DEMO}.pdf ${DEMO}.pmd'
pandoc  -V documentclass=article --number-sections --standalone -f markdown+startnum+smart+yaml_metadata_block --filter pandoc-fignos  -o ${DEMO}.pdf ${DEMO}.pmd

read -p "Press Any Key to see result" -n 1

${OPEN} ${DEMO}.pdf

